name: Update Home Assistant Schemas

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Tag or branch name'
        required: true
        default: 'main'
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4

      - name: Checkout vscode-home-assistant
        uses: actions/checkout@v4
        with:
          repository: keesschollaart81/vscode-home-assistant
          path: vscode-home-assistant
          ref: ${{ github.event.inputs.version || 'main' }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Compile schemas
        working-directory: vscode-home-assistant/src/language-service/
        run: |
          npm install
          npm run compile

      - name: Process and Copy schemas
        run: |
          mkdir -p json-schemas
          # Copy compiled JSON
          cp vscode-home-assistant/src/language-service/src/schemas/json/*.json json-schemas/
          # format use jq
          sudo apt-get install -y jq moreutils
          find json-schemas -type f -iname '*.json' -exec sh -c 'jq . "{}" | sponge "{}"' \;

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version || 'latest' }}
          name: "Home Assistant Schema ${{ github.event.inputs.version || 'Latest' }}"
          body: "Schemas are generated based on version/branch: ${{ github.event.inputs.version || 'main' }}"
          files: |
            json-schemas/*.json